when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/*

variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx'
  - &platforms_alpine 'linux/arm64/v8,linux/amd64'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username: smartinfrasolutions
        password:
          from_secret: docker_token
  - &publish_repos 'smartinfrasolutions/squid'

steps:

  - name: build-squid
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: *platforms_alpine
      tag: [latest]
      logins: *publish_logins
    when:
      - event: [pull_request, push]